# Generated by Django 5.2.11 on 2026-02-28 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=16, max_digits=65)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('next_payment', models.DateTimeField()),
                ('last_payment', models.DateTimeField(default=None, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_payments_out', to='accounts.account')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_payments_in', to='accounts.account')),
            ],
        ),
    ]
