# Generated by Django 5.2.11 on 2026-02-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_recurringpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringpayment',
            name='is_active',
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='deactivated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
