# Generated by Django 5.2.11 on 2026-02-28 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_recurringpayment_is_active_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetAddress',
            new_name='DepositEndpoint',
        ),
    ]
