# Generated by Django 5.2.11 on 2026-03-01 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_assetaddress_to_depositendpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdraw'), (3, 'Transfer'), (4, 'Internal Fee'), (5, 'Error Reversal'), (6, 'Custody Service Fee'), (7, 'Ln Payment Reversal')]),
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.IntegerField(choices=[(1, 'Usd'), (2, 'Eur'), (3, 'Chf')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('source', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.asset')),
            ],
            options={
                'indexes': [models.Index(fields=['asset', 'currency', 'timestamp'], name='accounts_pr_asset_i_30ca6a_idx')],
            },
        ),
    ]
