# Generated by Django 5.2.11 on 2026-03-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_transaction_tx_type_pricesnapshot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceSnapshot',
        ),
    ]
