# Generated by Django 5.2.11 on 2026-03-01 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_pricesnapshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outgoingtransaction',
            old_name='to_address',
            new_name='destination',
        ),
        migrations.AddField(
            model_name='outgoingtransaction',
            name='completed_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='outgoingtransaction',
            name='destination_type',
            field=models.IntegerField(choices=[(1, 'Onchain'), (2, 'Ln Invoice'), (3, 'Ln Address'), (4, 'Internal')], default=1),
        ),
        migrations.AddField(
            model_name='outgoingtransaction',
            name='failed_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='outgoingtransaction',
            name='failed_reason',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='outgoingtransaction',
            name='payment_preimage',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='outgoingtransaction',
            name='reversal_transaction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_outgoing', to='accounts.transaction'),
        ),
    ]
