# Generated by Django 5.2.11 on 2026-03-05 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_to_address_outgoingtransaction_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.IntegerField(choices=[(1, 'User'), (10, 'Onchain Incoming'), (11, 'Onchain Outgoing'), (20, 'Ln Incoming'), (21, 'Ln Outgoing'), (30, 'Fee')], default=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_transactions', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_transactions', to='accounts.account'),
        ),
    ]
