# Generated by Django 5.2.11 on 2026-03-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_account_type_alter_transaction_from_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingtransaction',
            name='review_reason',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='outgoingtransaction',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'In Flight'), (3, 'Completed'), (4, 'Failed'), (5, 'Pending Review')], default=1),
        ),
    ]
