# Generated by Django 5.2.11 on 2026-03-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_outgoingtransaction_review_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositendpoint',
            name='endpoint_type',
            field=models.IntegerField(choices=[(1, 'Onchain'), (2, 'Ln')], default=1),
        ),
    ]
