# Generated by Django 5.2.11 on 2026-03-05 14:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_depositendpoint_endpoint_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='parent_account',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_accounts', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='asset',
            name='ln_fee_floor',
            field=models.DecimalField(decimal_places=16, default=Decimal('1.0E-7'), max_digits=65),
        ),
        migrations.AddField(
            model_name='asset',
            name='ln_fee_percentage',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.01'), max_digits=8),
        ),
        migrations.AddField(
            model_name='outgoingtransaction',
            name='fee_actual',
            field=models.DecimalField(decimal_places=16, default=None, max_digits=65, null=True),
        ),
        migrations.AddField(
            model_name='outgoingtransaction',
            name='fee_charged',
            field=models.DecimalField(decimal_places=16, default=None, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.IntegerField(choices=[(1, 'User'), (10, 'Onchain Incoming'), (11, 'Onchain Outgoing'), (20, 'Ln Incoming'), (21, 'Ln Outgoing'), (30, 'Fee'), (31, 'Fee Credit')], default=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdraw'), (3, 'Transfer'), (4, 'Internal Fee'), (5, 'Error Reversal'), (6, 'Custody Service Fee'), (7, 'Ln Payment Reversal'), (8, 'Fee Rebate')]),
        ),
    ]
