# Generated by Django 5.2.11 on 2026-03-05 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_account_parent_account_asset_ln_fee_floor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='parent_account',
        ),
        migrations.AddField(
            model_name='account',
            name='fee_credit_account',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_credit_for', to='accounts.account'),
        ),
    ]
