# Generated by Django 5.2.11 on 2026-03-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_account_parent_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringpayment',
            name='to_account',
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='destination',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='destination_type',
            field=models.IntegerField(choices=[(1, 'Onchain'), (2, 'Ln Invoice'), (3, 'Ln Address'), (4, 'Internal')], default=1),
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
