# Generated by Django 5.2.11 on 2026-03-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_recurringpayment_to_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringpayment',
            name='amount_currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='amount_fiat',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20, null=True),
        ),
    ]
