# Generated by Django 5.2.11 on 2026-03-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_recurringpayment_amount_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringpayment',
            name='end_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
