# Generated by Django 5.2.11 on 2026-03-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_recurringpayment_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringpayment',
            name='frequency',
            field=models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], max_length=10),
        ),
    ]
