# Generated by Django 5.2.11 on 2026-03-10 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_recurringpayment_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringPaymentExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=16, max_digits=65)),
                ('amount_fiat', models.DecimalField(decimal_places=2, default=None, max_digits=20, null=True)),
                ('amount_currency', models.CharField(blank=True, default='', max_length=3)),
                ('error', models.TextField(blank=True, default='')),
                ('recurring_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='accounts.recurringpayment')),
                ('transaction', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.transaction')),
            ],
        ),
    ]
