# Generated by Django 5.2.11 on 2026-03-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_recurringpaymentexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingtransaction',
            name='batch_txid',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='outgoingtransaction',
            name='is_urgent',
            field=models.BooleanField(default=True),
        ),
    ]
