# Generated by Django 5.2.11 on 2026-03-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_add_batching_fields_to_outgoingtransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoingtransaction',
            name='batch_txid',
        ),
    ]
