# Generated by Django 5.2.11 on 2026-04-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_batch_txid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fiat_amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fiat_currency',
            field=models.CharField(default=None, max_length=4, null=True),
        ),
    ]
