# Generated by Django 5.2.11 on 2026-02-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllowanceSchedule',
        ),
    ]
