# Generated by Django 5.2.11 on 2026-03-05 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_delete_allowanceschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoltCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_name', models.CharField(blank=True, default='', max_length=255)),
                ('uid', models.CharField(max_length=14, unique=True)),
                ('k0', models.CharField(max_length=32)),
                ('k1', models.CharField(max_length=32)),
                ('k2', models.CharField(max_length=32)),
                ('prev_k0', models.CharField(default='00000000000000000000000000000000', max_length=32)),
                ('prev_k1', models.CharField(default='00000000000000000000000000000000', max_length=32)),
                ('prev_k2', models.CharField(default='00000000000000000000000000000000', max_length=32)),
                ('counter', models.IntegerField(default=0)),
                ('tx_limit', models.IntegerField(default=0, help_text='Max sats per transaction, 0 = no limit')),
                ('daily_limit', models.IntegerField(default=0, help_text='Max sats per day, 0 = no limit')),
                ('daily_spent', models.IntegerField(default=0)),
                ('daily_spent_date', models.DateField(default=None, null=True)),
                ('external_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('otp', models.CharField(blank=True, default='', max_length=32)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boltcards', to='wallets.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='BoltCardHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(default=None, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('old_counter', models.IntegerField()),
                ('new_counter', models.IntegerField()),
                ('amount_sats', models.IntegerField(default=0)),
                ('was_paid', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hits', to='wallets.boltcard')),
            ],
        ),
    ]
