# Generated by Django 5.2.11 on 2026-03-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_boltcard_boltcardhit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boltcard',
            name='k0',
        ),
        migrations.RemoveField(
            model_name='boltcard',
            name='k1',
        ),
        migrations.RemoveField(
            model_name='boltcard',
            name='k2',
        ),
        migrations.RemoveField(
            model_name='boltcard',
            name='prev_k0',
        ),
        migrations.RemoveField(
            model_name='boltcard',
            name='prev_k1',
        ),
        migrations.RemoveField(
            model_name='boltcard',
            name='prev_k2',
        ),
        migrations.AddField(
            model_name='boltcard',
            name='card_secret_hash',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='boltcard',
            name='k0_enc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='boltcard',
            name='k1_enc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='boltcard',
            name='k2_enc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='boltcard',
            name='prev_k0_enc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='boltcard',
            name='prev_k1_enc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='boltcard',
            name='prev_k2_enc',
            field=models.TextField(default=''),
        ),
    ]
