# Generated by Django 5.2.11 on 2026-03-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_remove_boltcard_k0_remove_boltcard_k1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boltcard',
            name='card_name',
        ),
    ]
