# Generated by Django 5.2.11 on 2026-03-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_convert_public_id_to_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boltcard',
            name='uid',
            field=models.CharField(db_index=True, max_length=14),
        ),
    ]
