# Generated by Django 5.2.11 on 2026-03-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0008_alter_boltcard_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='default_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CHF', 'CHF')], default='USD', max_length=3),
        ),
    ]
