# Generated by Django 5.2.11 on 2026-03-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0009_wallet_default_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='default_currency',
        ),
        migrations.AddField(
            model_name='wallet',
            name='primary_currency',
            field=models.CharField(choices=[('BTC', 'BTC'), ('sats', 'sats'), ('USD', 'USD'), ('EUR', 'EUR'), ('CHF', 'CHF')], default='CHF', max_length=4),
        ),
        migrations.AddField(
            model_name='wallet',
            name='secondary_currency',
            field=models.CharField(choices=[('BTC', 'BTC'), ('sats', 'sats'), ('USD', 'USD'), ('EUR', 'EUR'), ('CHF', 'CHF')], default='BTC', max_length=4),
        ),
    ]
