# Generated by Django 5.2.11 on 2026-03-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0010_remove_wallet_default_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_banner', models.TextField(blank=True, default='This is a demo instance meant for educational and testing purposes only.', help_text='Text displayed on the wallet info page. Leave empty to hide.')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
