# Generated by Django 5.2.11 on 2026-03-25 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_batch_txid'),
        ('wallets', '0011_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='boltcardhit',
            name='transaction',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.transaction'),
        ),
    ]
