# Generated by Django 5.2.11 on 2026-09-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0012_boltcardhit_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='boltcard',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
